name: anecdotal
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.4.0
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  google_generative_ai: ^0.4.5
  http: ^1.2.2
  fl_chart: ^0.69.0
  gap: ^3.0.1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  record: ^5.1.2
  path_provider: ^2.0.15
  path: ^1.9.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  file_picker: ^8.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0
# To launch run: dart run flutter_native_splash:create
  flutter_native_splash: ^2.4.1
# To launch run: flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
flutter_native_splash:
  color: "#006666"
  image: "assets/images/anecdotal_logo_rounded_800x800.png"
flutter_icons:
  image_path: "assets/images/anecdotal_logo.png"
  android: true
  ios: true
  web:
   generate: true
   image_path: "assets/images/anecdotal_logo.png"
   
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          style: italic
