name: anecdotal
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.33+34

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.4.1
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  fl_chart: ^0.69.0
  gap: ^3.0.1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  record: ^5.1.2
  path_provider: ^2.0.15
  path: ^1.9.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  file_picker: ^8.0.7
  flutter_advanced_drawer: ^1.3.6
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.2.1
  shared_preferences: ^2.3.2
  toastification: ^2.2.0
  url_strategy: ^0.3.0
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  camerawesome: ^2.1.0
  purchases_flutter: ^8.1.1
  purchases_ui_flutter: ^8.1.1
  freezed_annotation: any
  intl: ^0.19.0
  timeline_tile: ^2.0.0
  firebase_storage: ^12.3.0
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.0.2
  chewie: ^1.8.5
  upgrader: ^11.1.0
  cached_network_image: ^3.4.1
  flutter_chat_ui: ^1.6.15
  flutter_firebase_chat_core: ^1.6.8
  flutter_chat_types: ^3.6.2
  open_filex: ^4.5.0
  uuid: ^4.5.0
  mime: ^1.0.6
  photo_view: ^0.15.0
  syncfusion_flutter_pdfviewer: ^27.1.48
  # firebase_crashlytics: ^4.1.2
  firebase_analytics: ^11.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0
# To launch run: dart run flutter_native_splash:create
  flutter_native_splash: ^2.4.1
# To launch run: flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
flutter_native_splash:
  color: "#212121"
  image: "assets/images/logo_circle_1080.png"
flutter_icons:
  image_path: "assets/images/anecdotal_512.png"
  android: true
  ios: true
  web:
   generate: true
   image_path: "assets/images/logo_circle_1080.png"
   
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          style: italic
